import { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './experience.css'
import './components/decision-execution.css'
import DecisionExecutionSequence from './components/DecisionExecutionSequence'
import RecoveryIntelligenceGraph from './components/RecoveryIntelligenceGraph/RecoveryIntelligenceGraph'
import CounterfactualLab from './components/CounterfactualLab/CounterfactualLab'
import AIRecoveryAdvisor from './components/AIRecoveryAdvisor/AIRecoveryAdvisor'
import { GraphTransactionContext } from './types/graph'
import { createTransaction } from './recoveryEngine'

type Result='Recovered'|'Stopped'|'Pending'
type EventItem={id:string;amount:number;reason:string;action:string;result:Result;confidence:number;latency:string;recoveryProbability:number;riskScore:number;policy:'Approved'|'Escalated';explanation:string}
type Scenario='balanced'|'checkout'|'degradation'
const makeEvents=(scenario:Scenario='balanced'):EventItem[]=>Array.from({length:100},(_,i)=>createTransaction(i,scenario))
const seed=makeEvents('balanced'), money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`, stageAt=(p:number)=>p<20?'DETECT':p<40?'DIAGNOSE':p<60?'DECIDE':p<80?'RECOVER':'VERIFY'
const scenarios={balanced:{label:'Balanced',mult:1,desc:'Mixed payment failures with conservative policy gates'},checkout:{label:'Checkout drop-off',mult:1.12,desc:'Higher abandoned-checkout volume with payment-link recovery'},degradation:{label:'Gateway degradation',mult:.82,desc:'Transient bank and issuer failures with retry-first recovery'}} as const

function App(){
 const[events,setEvents]=useState(seed),[running,setRunning]=useState(false),[progress,setProgress]=useState(0),[tab,setTab]=useState('Overview'),[selected,setSelected]=useState<EventItem|null>(seed[0]),[scenario,setScenario]=useState<Scenario>('balanced'),[toast,setToast]=useState('')
 const[cfTransaction,setCfTransaction]=useState<GraphTransactionContext|null>(null),[cfTarget,setCfTarget]=useState<'original'|'counterfactual'>('counterfactual'),[cfRunning,setCfRunning]=useState(false),[cfProgress,setCfProgress]=useState(100)
 const raf=useRef<number|null>(null)
 useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current)},[])
 const handleCfSync=(target:'original'|'counterfactual',cfTxn:GraphTransactionContext|null,isRunning:boolean,p:number)=>{setCfTarget(target);setCfTransaction(cfTxn);setCfRunning(isRunning);setCfProgress(p)}
 const run=()=>{if(running)return;const fresh=makeEvents(scenario);setRunning(true);setProgress(0);setSelected(null);setEvents(fresh.map(e=>({...e,result:'Pending'})));const start=performance.now();const tick=(now:number)=>{const p=Math.min(100,((now-start)/6200)*100);setProgress(p);const completed=Math.floor(p);if(completed>0)setEvents(current=>current.map((e,i)=>i<completed?fresh[i]:{...e,result:'Pending'}));if(p<100)raf.current=requestAnimationFrame(tick);else{setRunning(false);setEvents(fresh);setToast('Batch verified · recovery ledger updated');window.setTimeout(()=>setToast(''),2200)}};raf.current=requestAnimationFrame(tick)}
 const processed=Math.floor(progress),done=events.slice(0,processed||(!running?100:0)),mult=scenarios[scenario].mult,recovered=Math.round((done.filter(e=>e.result==='Recovered').reduce((s,e)=>s+e.amount,0) || 86400)*mult),risk=Math.round((done.reduce((s,e)=>s+e.amount,0)||240000)*mult),rate=done.length?Math.min(99,Math.round(recovered/risk*100)):36,stopped=done.filter(e=>e.result==='Stopped').length,stage=stageAt(progress),visible=useMemo(()=>events.slice(0,10),[events]),complete=progress>=100&&!running
 const chart=useMemo(()=>{const n=14;return Array.from({length:n},(_,i)=>{const p=complete?1:progress/100;const wave=Math.sin(i*.75+scenario.length)*6;return Math.max(8,Math.min(92,18+i*5.1*p+wave*p))})},[progress,complete,scenario])
 const selectScenario=(s:Scenario)=>{if(running)return;const next=makeEvents(s);setScenario(s);setProgress(0);setEvents(next);setSelected(next[0]);setToast(`${scenarios[s].label} scenario armed`);window.setTimeout(()=>setToast(''),1600)}
 return <div className="app"><header className="nav"><div className="logo"><span className="logoMark">R</span><span>RazorRecover</span><em>AI</em></div><div className="navTabs">{['Overview','Simulation','Agent trace','Audit trail'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="live"><span/> {running?`PROCESSING · ${Math.floor(progress)}%`:complete?'LIVE · COMPLETE':'LIVE · SYNTHETIC MODE'}</div></header>
 <main className="shell"><section className="hero"><div className="heroCopy"><div className="eyebrow">REVENUE RECOVERY / 01</div><h1>Recover revenue.<br/><i>Intelligently.</i></h1><p>An autonomous recovery agent that detects leakage, diagnoses root causes, applies bounded interventions, and proves the money recovered.</p></div><div className="heroAction"><div className="health"><span/> All systems nominal <b>·</b> 42ms</div><button className="run" onClick={run} disabled={running}><span>{running?`Processing ${Math.floor(progress)}%`:complete?'Run again':'Run live simulation'}</span><b>↗</b></button></div></section>
 <section className="metrics"><Metric label="Revenue at risk" value={money(risk)} note={`${processed||100} synthetic events`}/><Metric label="Money recovered" value={money(recovered)} note="Verified recoveries" good/><Metric label="Recovery rate" value={`${rate}%`} note="Target: >30%" gold/><Metric label="Actions gated" value={String(stopped||8).padStart(2,'0')} note="Stopped / escalated" danger/></section>
 <section className="panel lab"><div className="panelTop"><div><span className="eyebrow">RECOVERY LAB</span><h2>Choose a failure environment</h2></div><span className="pulse">● deterministic</span></div><div className="scenarioBar">{(Object.keys(scenarios) as Scenario[]).map(s=><button className={`scenario ${scenario===s?'active':''}`} onClick={()=>selectScenario(s)} key={s}><strong>{s==='balanced'?'01':s==='checkout'?'02':'03'}</strong>{scenarios[s].label}</button>)}</div><div className="scenarioMeta"><div><span>MODE</span><b>{scenarios[scenario].label}</b></div><div><span>POLICY</span><b>Bounded</b></div><div><span>DATA</span><b>100 events</b></div><div><span>FUNDS</span><b>Synthetic</b></div></div><div className="pulseChart"><span className="chartLabel">RECOVERY VELOCITY</span><span className="chartValue">{rate}% verified</span><div className="spark"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={chart.map((v,i)=>`${i*(100/(chart.length-1))},${100-v}`).join(' ')}/><circle cx={100} cy={100-chart[chart.length-1]} r="2.3"/></svg></div></div></section>
 <section className="coreGrid"><div className="panel corePanel"><div className="panelTop"><div><span className="eyebrow">AGENT CORE</span><h2>Revenue recovery engine</h2></div><span className="secure">● BOUNDED · SAFE</span></div><RecoveryIntelligenceGraph transaction={cfTarget==='counterfactual'&&cfTransaction?cfTransaction:selected} progress={cfRunning?cfProgress:progress} running={cfRunning||running} complete={cfRunning?cfProgress>=100:complete} /></div>
 <div className="panel tracePanel"><div className="panelTop"><div><span className="eyebrow">AI JUDGEMENT</span><h2>{tab==='Overview'?'Latest decisions':tab}</h2></div><span className="pulse">● {running?'processing':'streaming'}</span></div>{tab==='Overview'&&<><div className="traceList"><Trace title="Root cause detected" text={`${scenarios[scenario].label} · retry permitted`} tag={selected?`${selected.confidence}%`:'94%'}/><Trace title="Policy gate evaluated" text={selected?.explanation||'Idempotency ✓ · attempts 1/2 · low risk'} tag={selected?.policy==='Approved'?'SAFE':'ESCALATE'} stop={selected?.policy==='Escalated'}/><Trace title="Recovery intervention" text={selected?.action||'Bounded intervention · verification pending'} tag={selected?.result==='Recovered'?'DONE':'READY'}/><Trace title="Safety boundary" text={selected?.riskScore?`Risk ${selected.riskScore}/100 · no uncontrolled money movement`:'Retry limit reached · human escalation'} tag={selected?.riskScore&&selected.riskScore<70?'PASS':'STOP'} stop={!!selected?.riskScore&&selected.riskScore>=70}/></div><div className="policy"><span>POLICY ENGINE</span><b>Every money action is explainable, bounded & gated.</b><div><i>✓</i> No duplicate charge&nbsp;&nbsp; <i>✓</i> Max 2 retries&nbsp;&nbsp; <i>✓</i> Audit event</div></div></>}{tab==='Simulation'&&<SimulationInfo progress={progress} running={running} scenario={scenarios[scenario].label}/>} {tab==='Agent trace'&&<AgentTrace progress={progress}/>} {tab==='Audit trail'&&<AuditTrail progress={progress}/>}</div></section>
 <section className="panel transactions"><div className="panelTop"><div><span className="eyebrow">EVENT STREAM</span><h2>Recovery operations</h2></div><span>{processed||100} / 100 synthetic transactions</span></div><div className="table">{visible.map(e=><button className={`row ${selected?.id===e.id?'selected':''}`} key={e.id} onClick={()=>setSelected(e)}><strong>{e.id}</strong><b>{money(e.amount)}</b><span>{e.reason}</span><span className="action">→ {e.action}</span><span className={`status ${e.result.toLowerCase()}`}>{e.result}</span><span className="confidence">{e.confidence}%</span></button>)}</div></section>
 {selected&&<section className="detailStrip"><div><span className="eyebrow">SELECTED EVENT</span><strong>{selected.id}</strong></div><div><small>ROOT CAUSE</small><b>{selected.reason}</b></div><div><small>AI CONFIDENCE</small><b>{selected.confidence}%</b></div><div><small>RECOVERY PROB.</small><b>{selected.recoveryProbability}%</b></div><div><small>RISK SCORE</small><b>{selected.riskScore}/100</b></div><div><small>POLICY RESULT</small><b className={selected.result==='Recovered'?'goodText':selected.result==='Stopped'?'dangerText':'goldText'}>{selected.result}</b></div></section>}
 {selected&&<AIRecoveryAdvisor transaction={selected} />}
 {selected&&<DecisionExecutionSequence key={`${selected.id}-${selected.amount}`} amount={selected.amount}/>}
 {selected&&<CounterfactualLab originalTransaction={selected} onActiveGraphTargetChange={handleCfSync} />}
 <footer>RAZORRECOVER AI · SYNTHETIC DATA · NO REAL CUSTOMER FUNDS · BUILDATHON PROTOTYPE</footer></main>{toast&&<div className="toast"><b>✓</b>{toast}</div>}</div>
}
function Metric({label,value,note,good,gold,danger}:{label:string,value:string,note:string,good?:boolean,gold?:boolean,danger?:boolean}){return <div className="metric"><span>{label}</span><strong className={good?'good':gold?'gold':danger?'danger':''}>{value}</strong><small>{note}</small></div>}
function Trace({title,text,tag,stop}:{title:string,text:string,tag:string,stop?:boolean}){return <div className="trace"><span className={stop?'dot stop':'dot'}/><div><b>{title}</b><small>{text}</small></div><em className={stop?'tag stopTag':'tag'}>{tag}</em></div>}
function SimulationInfo({progress,running,scenario}:{progress:number,running:boolean,scenario:string}){return <div className="infoView"><div className="bigProgress">{Math.floor(progress)}<small>%</small></div><p>{running?`Processing the ${scenario} environment through detection, diagnosis, decision, recovery and verification.`:`Launch the simulation to watch 100 synthetic transactions move through the complete recovery pipeline.`}</p><div className="miniStats"><span>100 <small>transactions</small></span><span>5 <small>AI stages</small></span><span>0 <small>real funds</small></span></div></div>}
function AgentTrace({progress}:{progress:number}){const lines=['Event ingested from payment stream','AI diagnosis requested','AI intervention recommendation received','Policy gate evaluated','Recovery action bounded and logged'];return <div className="traceList">{lines.map((line,i)=><div className="trace" key={line}><span className={progress>i*20?'dot':'dot muted'}/><div><b>{line}</b><small>{progress>i*20?'completed · evidence attached':'waiting for simulation stage'}</small></div><em className="tag">{progress>i*20?'DONE':'WAIT'}</em></div>)}</div>}
function AuditTrail({progress}:{progress:number}){const status=progress>=100?'verified':progress>0?'processing':'ready';return <div className="audit"><div><b>09:41:02.481</b><span>TXN-1042 · diagnosis.created</span><em>hash: 9f2a…e81c</em></div><div><b>09:41:02.901</b><span>TXN-1042 · policy.approved</span><em>rule: retry_limit_2</em></div><div><b>09:41:03.212</b><span>TXN-1042 · recovery.{status}</span><em>amount: ₹2,499</em></div><div><b>09:41:05.004</b><span>TXN-1040 · recovery.stopped</span><em>reason: max_attempts</em></div></div>}
createRoot(document.getElementById('root')!).render(<App />)
