import { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

type Result = 'Recovered' | 'Stopped' | 'Pending'
type EventItem = { id: string; amount: number; reason: string; action: string; result: Result; confidence: number; latency: string }
const reasons = [['Bank timeout','Retry payment'],['Checkout abandoned','Payment link'],['Retry limit reached','Escalate'],['Network degradation','Retry payment'],['Authentication failed','Customer prompt'],['Subscription failure','Retry + link'],['Insufficient balance','Payment link'],['3DS challenge expired','Customer prompt'],['Issuer unavailable','Retry payment'],['Velocity risk','Escalate']] as const
const makeEvents = (): EventItem[] => Array.from({length:100},(_,i)=>{const [reason,action]=reasons[i%reasons.length];const stopped=i%17===0||i%29===0;const pending=!stopped&&i%13===0;return{id:`TXN-${String(1042-i).padStart(4,'0')}`,amount:799+((i*1703)%18000),reason,action,result:stopped?'Stopped':pending?'Pending':'Recovered',confidence:82+((i*7)%18),latency:`${180+((i*43)%520)}ms`}})
const seed=makeEvents();const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`;const stageAt=(p:number)=>p<20?'DETECT':p<40?'DIAGNOSE':p<60?'DECIDE':p<80?'RECOVER':'VERIFY'
function App(){const[events,setEvents]=useState(seed),[running,setRunning]=useState(false),[progress,setProgress]=useState(0),[tab,setTab]=useState('Overview'),[selected,setSelected]=useState<EventItem|null>(seed[0]);const raf=useRef<number|null>(null);useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current)},[])
const run=()=>{if(running)return;setRunning(true);setProgress(0);setSelected(null);setEvents(seed.map(e=>({...e,result:'Pending'})));const start=performance.now();const tick=(now:number)=>{const p=Math.min(100,((now-start)/5200)*100);setProgress(p);const completed=Math.floor(p);if(completed>0)setEvents(seed.map((e,i)=>i<completed?e:{...e,result:'Pending'}));if(p<100)raf.current=requestAnimationFrame(tick);else setRunning(false)};raf.current=requestAnimationFrame(tick)}
const processed=Math.floor(progress),done=events.slice(0,processed||(!running?100:0)),recovered=done.filter(e=>e.result==='Recovered').reduce((s,e)=>s+e.amount,0),risk=done.reduce((s,e)=>s+e.amount,0)||240000,rate=done.length?Math.round(recovered/risk*100):36,stopped=done.filter(e=>e.result==='Stopped').length,stage=stageAt(progress),visible=useMemo(()=>events.slice(0,10),[events]),complete=progress>=100&&!running
return <div className="app"><header className="nav"><div className="logo"><span className="logoMark">R</span><span>RazorRecover</span><em>AI</em></div><div className="navTabs">{['Overview','Simulation','Agent trace','Audit trail'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="live"><span/> {running?`PROCESSING · ${Math.floor(progress)}%`:complete?'LIVE · COMPLETE':'LIVE · SYNTHETIC MODE'}</div></header>
<main className="shell"><section className="hero"><div className="heroCopy"><div className="eyebrow">REVENUE RECOVERY / 01</div><h1>Recover revenue.<br/><i>Intelligently.</i></h1><p>An autonomous recovery agent that detects leakage, diagnoses root causes, applies bounded interventions, and proves the money recovered.</p></div><div className="heroAction"><div className="health"><span/> All systems nominal <b>·</b> 42ms</div><button className="run" onClick={run} disabled={running}><span>{running?`Processing ${Math.floor(progress)}%`:complete?'Run again':'Run live simulation'}</span><b>↗</b></button></div></section>
<section className="metrics"><Metric label="Revenue at risk" value={money(risk)} note={`${processed||100} synthetic events`}/><Metric label="Money recovered" value={money(recovered||86400)} note="Verified recoveries" good/><Metric label="Recovery rate" value={`${rate}%`} note="Target: >30%" gold/><Metric label="Actions gated" value={String(stopped||8).padStart(2,'0')} note="Stopped / escalated" danger/></section>
<section className="coreGrid"><div className="panel corePanel"><div className="panelTop"><div><span className="eyebrow">AGENT CORE</span><h2>Revenue recovery engine</h2></div><span className="secure">● BOUNDED · SAFE</span></div><div className="coreVisual"><div className={`orb ${running?'active':''}`}><div className="orbGlow"/><div className="orbInner"><strong>{running?Math.floor(progress):'AI'}</strong><small>{running?stage:complete?'DONE':'READY'}</small></div></div><div className="ring r1"/><div className="ring r2"/><div className="ring r3"/><div className="orbitDot od1"/><div className="orbitDot od2"/><div className="orbitDot od3"/><div className="node n1"><span>01</span>DETECT</div><div className="node n2"><span>02</span>DIAGNOSE</div><div className="node n3"><span>03</span>DECIDE</div><div className="node n4"><span>04</span>RECOVER</div><div className="coreGridLabel">AUTONOMOUS<br/><b>RECOVERY CORE</b></div></div><div className="pipeline">{['Detect','Diagnose','Decide','Recover','Verify'].map((x,i)=><div className={progress>=(i+1)*20?'step done':'step'} key={x}><span>{String(i+1).padStart(2,'0')}</span>{x}</div>)}</div></div>
<div className="panel tracePanel"><div className="panelTop"><div><span className="eyebrow">AI JUDGEMENT</span><h2>{tab==='Overview'?'Latest decisions':tab}</h2></div><span className="pulse">● {running?'processing':'streaming'}</span></div>{tab==='Overview'&&<><div className="traceList"><Trace title="Root cause detected" text="Transient bank failure · retry permitted" tag="94%"/><Trace title="Policy gate passed" text="Idempotency ✓ · attempts 1/2 · low risk" tag="SAFE"/><Trace title="Recovery executed" text="Retry payment · ₹2,499" tag={progress>=60?'DONE':'READY'}/><Trace title="Safety stop" text="Retry limit reached · human escalation" tag="STOP" stop/></div><div className="policy"><span>POLICY ENGINE</span><b>Every money action is explainable, bounded & gated.</b><div><i>✓</i> No duplicate charge&nbsp;&nbsp; <i>✓</i> Max 2 retries&nbsp;&nbsp; <i>✓</i> Audit event</div></div></>}{tab==='Simulation'&&<SimulationInfo progress={progress} running={running}/>} {tab==='Agent trace'&&<AgentTrace progress={progress}/>} {tab==='Audit trail'&&<AuditTrail/>}</div></section>
<section className="panel transactions"><div className="panelTop"><div><span className="eyebrow">EVENT STREAM</span><h2>Recovery operations</h2></div><span>{processed||100} / 100 synthetic transactions</span></div><div className="table">{visible.map(e=><button className={`row ${selected?.id===e.id?'selected':''}`} key={e.id} onClick={()=>setSelected(e)}><strong>{e.id}</strong><b>{money(e.amount)}</b><span>{e.reason}</span><span className="action">→ {e.action}</span><span className={`status ${e.result.toLowerCase()}`}>{e.result}</span><span className="confidence">{e.confidence}%</span></button>)}</div></section>
{selected&&<section className="detailStrip"><div><span className="eyebrow">SELECTED EVENT</span><strong>{selected.id}</strong></div><div><small>ROOT CAUSE</small><b>{selected.reason}</b></div><div><small>AI CONFIDENCE</small><b>{selected.confidence}%</b></div><div><small>LATENCY</small><b>{selected.latency}</b></div><div><small>POLICY RESULT</small><b className={selected.result==='Recovered'?'goodText':selected.result==='Stopped'?'dangerText':'goldText'}>{selected.result}</b></div></section>}<footer>RAZORRECOVER AI · SYNTHETIC DATA · NO REAL CUSTOMER FUNDS · BUILDATHON PROTOTYPE</footer></main></div>}
function Metric({label,value,note,good,gold,danger}:{label:string,value:string,note:string,good?:boolean,gold?:boolean,danger?:boolean}){return <div className="metric"><span>{label}</span><strong className={good?'good':gold?'gold':danger?'danger':''}>{value}</strong><small>{note}</small></div>}
function Trace({title,text,tag,stop}:{title:string,text:string,tag:string,stop?:boolean}){return <div className="trace"><span className={stop?'dot stop':'dot'}/><div><b>{title}</b><small>{text}</small></div><em className={stop?'tag stopTag':'tag'}>{tag}</em></div>}
function SimulationInfo({progress,running}:{progress:number,running:boolean}){return <div className="infoView"><div className="bigProgress">{Math.floor(progress)}<small>%</small></div><p>{running?'Processing synthetic transactions through the complete recovery pipeline.':'Launch the simulation to watch 100 synthetic transactions move through detection, diagnosis, decision, recovery and verification.'}</p><div className="miniStats"><span>100 <small>transactions</small></span><span>5 <small>AI stages</small></span><span>0 <small>real funds</small></span></div></div>}
function AgentTrace({progress}:{progress:number}){const lines=['Event ingested from payment stream','Failure classified as transient','Customer intent + risk scored','Policy gate evaluated','Recovery action bounded and logged'];return <div className="traceList">{lines.map((line,i)=><div className="trace" key={line}><span className={progress>i*20?'dot':'dot muted'}/><div><b>{line}</b><small>{progress>i*20?'completed · deterministic evidence attached':'waiting for simulation stage'}</small></div><em className="tag">{progress>i*20?'DONE':'WAIT'}</em></div>)}</div>}
function AuditTrail(){return <div className="audit"><div><b>09:41:02.481</b><span>TXN-1042 · diagnosis.created</span><em>hash: 9f2a…e81c</em></div><div><b>09:41:02.901</b><span>TXN-1042 · policy.approved</span><em>rule: retry_limit_2</em></div><div><b>09:41:03.212</b><span>TXN-1042 · recovery.verified</span><em>amount: ₹2,499</em></div><div><b>09:41:05.004</b><span>TXN-1040 · recovery.stopped</span><em>reason: max_attempts</em></div></div>}
createRoot(document.getElementById('root')!).render(<App />)
