import { useEffect, useMemo, useRef, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './experience.css'
import './components/decision-execution.css'
import './components/recovery-playbooks.css'
import DecisionExecutionSequence from './components/DecisionExecutionSequence'
import RecoveryIntelligenceGraph from './components/RecoveryIntelligenceGraph/RecoveryIntelligenceGraph'
import CounterfactualLab from './components/CounterfactualLab/CounterfactualLab'
import AIRecoveryAdvisor from './components/AIRecoveryAdvisor/AIRecoveryAdvisor'
import { GraphTransactionContext } from './types/graph'
import { createTransaction, type RecoveryDirection } from './recoveryEngine'

type Result='Recovered'|'Stopped'|'Pending'
type Scenario='balanced'|'checkout'|'degradation'
type WorkflowStatus='READY'|'RUNNING'|'COMPLETE'|'ESCALATED'
type EventItem=ReturnType<typeof createTransaction> & { workflowStatus?:WorkflowStatus; workflowMessage?:string; workflowAction?:string; verifiedAmount?:number }
type AuditItem={time:string;event:string;detail:string;status:'INFO'|'PASS'|'STOP'|'LIVE'}

const scenarios={balanced:{label:'Balanced'},checkout:{label:'Checkout drop-off'},degradation:{label:'Gateway degradation'}} as const
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
const makeEvents=(scenario:Scenario):EventItem[]=>Array.from({length:100},(_,i)=>createTransaction(i,scenario))
const directions:Array<{id:RecoveryDirection;short:string;description:string;steps:string[];action:string;tone:'gold'|'green'|'red'}>=[
{id:'Payment degradation',short:'Gateway recovery',description:'Detect issuer degradation, isolate the fault and retry only inside policy limits.',steps:['Detect elevated failures','Cluster bank / issuer root cause','Gate retry by risk + attempts','Verify recovered payment'],action:'Run gateway recovery',tone:'gold'},
{id:'Checkout drop-off',short:'Checkout recovery',description:'Recover high-intent abandoned checkouts without duplicating a payment attempt.',steps:['Identify abandoned checkout','Score purchase intent','Issue recovery link','Verify conversion'],action:'Recover checkout',tone:'gold'},
{id:'Failed-subscription recovery',short:'Subscription recovery',description:'Move past-due subscriptions through bounded retry and recovery-link steps.',steps:['Detect past-due state','Choose retry window','Retry or recovery link','Confirm restored'],action:'Recover subscription',tone:'green'},
{id:'B2B receivables chaser',short:'B2B collections',description:'Prioritize overdue invoices, draft the right chase and escalate risky receivables.',steps:['Age receivable','Score account risk','Send contextual reminder','Escalate unresolved invoice'],action:'Run AR chase',tone:'green'},
{id:'Mandate retry sequencer',short:'Mandate recovery',description:'Sequence mandate retries with a hard retry ceiling and safe fallback.',steps:['Classify mandate failure','Select retry window','Respect retry ceiling','Fallback payment link'],action:'Sequence mandate',tone:'gold'},
{id:'Hinglish voice recovery',short:'Hinglish voice',description:'Prepare a concise bilingual, consent-safe recovery conversation.',steps:['Detect high intent','Prepare Hinglish script','Read consent-safe prompt','Send recovery link'],action:'Play Hinglish script',tone:'green'},
{id:'Promise-to-pay tracker',short:'Promise to pay',description:'Capture a promised payment date and escalate only when the promise is missed.',steps:['Record promise','Set due date','Track status','Escalate missed promise'],action:'Create PTP',tone:'red'}]

function App(){
 const seed=useMemo(()=>makeEvents('balanced'),[])
 const [events,setEvents]=useState<EventItem[]>(seed),[selected,setSelected]=useState<EventItem|null>(seed[0]),[scenario,setScenario]=useState<Scenario>('balanced'),[running,setRunning]=useState(false),[progress,setProgress]=useState(0),[tab,setTab]=useState('Overview'),[toast,setToast]=useState('')
 const [audit,setAudit]=useState<AuditItem[]>([]),[activeDirection,setActiveDirection]=useState<RecoveryDirection|null>(null),[workflowStatus,setWorkflowStatus]=useState<WorkflowStatus>('READY'),[workflowMessage,setWorkflowMessage]=useState('Choose a recovery direction. Its actions write back to the same ledger, graph, event stream and audit trail.'),[ptpDate,setPtpDate]=useState(()=>new Date(Date.now()+86400000*3).toISOString().slice(0,10)),[ptpState,setPtpState]=useState<'PROMISED'|'PAID'|'MISSED'>('PROMISED'),[voicePlaying,setVoicePlaying]=useState(false)
 const [cfTransaction,setCfTransaction]=useState<GraphTransactionContext|null>(null),[cfTarget,setCfTarget]=useState<'original'|'counterfactual'>('counterfactual'),[cfRunning,setCfRunning]=useState(false),[cfProgress,setCfProgress]=useState(100)
 const raf=useRef<number|null>(null)
 useEffect(()=>()=>{if(raf.current)cancelAnimationFrame(raf.current)},[])
 const addAudit=(event:string,detail:string,status:AuditItem['status']='INFO')=>setAudit(a=>[{time:new Date().toLocaleTimeString('en-IN',{hour12:false}),event,detail,status},...a].slice(0,12))
 const processed=Math.floor(progress),riskEvents=running?events.slice(0,processed):events,risk=riskEvents.reduce((s,e)=>s+e.amount,0),recovered=riskEvents.reduce((s,e)=>s+(e.verifiedAmount??(e.result==='Recovered'?e.amount:0)),0),rate=risk?Math.min(99,Math.round(recovered/risk*100)):0,stopped=riskEvents.filter(e=>e.result==='Stopped').length,complete=progress>=100&&!running,visible=useMemo(()=>events.slice(0,10),[events])
 const recoveredEvents=riskEvents.filter(e=>(e.verifiedAmount??(e.result==='Recovered'?e.amount:0))>0),velocity=recoveredEvents.length?Math.round(recoveredEvents.reduce((s,e)=>s+(e.verifiedAmount??e.amount),0)/(recoveredEvents.reduce((s,e)=>s+Number.parseInt(e.latency,10),0)/1000)):0,velocityLabel=velocity?`${money(velocity)}/s`:'—'
 const velocityScore=velocity?Math.min(92,Math.max(8,Math.round((velocity/Math.max(1,risk))*10000))):8
 const chart=useMemo(()=>Array.from({length:14},(_,i)=>{const p=complete?1:running?progress/100:0;return Math.max(8,Math.min(92,8+(velocityScore-8)*p+Math.sin(i*.75+scenario.length)*3*p))}),[progress,complete,running,velocityScore,scenario])
 const handleCfSync=(target:'original'|'counterfactual',txn:GraphTransactionContext|null,isRunning:boolean,p:number)=>{setCfTarget(target);setCfTransaction(txn);setCfRunning(isRunning);setCfProgress(p)}
 const selectScenario=(s:Scenario)=>{if(running)return;const next=makeEvents(s);setScenario(s);setProgress(0);setEvents(next);setSelected(next[0]);setActiveDirection(null);setWorkflowStatus('READY');setWorkflowMessage('Scenario armed. Choose a recovery direction to write into the shared ledger.');addAudit('scenario.armed',scenarios[s].label,'INFO')}
 const run=()=>{if(running)return;const fresh=makeEvents(scenario);setRunning(true);setProgress(0);setSelected(null);setEvents(fresh.map(e=>({...e,result:'Pending' as Result,verifiedAmount:0,workflowStatus:'READY' as WorkflowStatus})));addAudit('batch.started',`${scenarios[scenario].label} · 100 synthetic transactions`,'LIVE');const start=performance.now();const tick=(now:number)=>{const p=Math.min(100,((now-start)/6200)*100);setProgress(p);const n=Math.floor(p);if(n>0)setEvents(current=>current.map((e,i)=>i<n?fresh[i]:{...e,result:'Pending' as Result}));if(p<100)raf.current=requestAnimationFrame(tick);else{setRunning(false);setEvents(fresh.map(e=>({...e,verifiedAmount:e.result==='Recovered'?e.amount:0,workflowStatus:'READY' as WorkflowStatus})));addAudit('batch.verified','Shared recovery ledger verified','PASS');setToast('Batch verified · shared ledger updated');window.setTimeout(()=>setToast(''),1800)}};raf.current=requestAnimationFrame(tick)}
 const selectPlaybook=(d:RecoveryDirection)=>{if(running)return;const sample=createTransaction(directions.findIndex(x=>x.id===d),scenario);const existing=events.find(e=>e.id===sample.id);setActiveDirection(d);setWorkflowStatus('READY');setWorkflowMessage('Workflow armed. Run the bounded action to propagate its result through the same product.');setSelected(existing??sample);addAudit('workflow.armed',`${d} → ${sample.id}`,'INFO')}
 const applyWorkflow=(id:string,status:WorkflowStatus,message:string,action:string,verifiedAmount=0)=>{setWorkflowStatus(status);setWorkflowMessage(message);setEvents(current=>current.map(e=>e.id===id?{...e,workflowStatus:status,workflowMessage:message,workflowAction:action,action,explanation:`${e.explanation} Workflow: ${message}`,verifiedAmount}:e));setSelected(current=>current&&current.id===id?{...current,workflowStatus:status,workflowMessage:message,workflowAction:action,action,explanation:`${current.explanation} Workflow: ${message}`,verifiedAmount}:current);addAudit(`workflow.${status.toLowerCase()}`,`${activeDirection} · ${id}`,status==='COMPLETE'?'PASS':status==='ESCALATED'?'STOP':'LIVE');setToast(`${activeDirection} · ${status.toLowerCase()}`);window.setTimeout(()=>setToast(''),1800)}
 const runWorkflow=async()=>{if(!activeDirection||workflowStatus==='RUNNING')return;const sample=createTransaction(directions.findIndex(x=>x.id===activeDirection),scenario);const id=sample.id;if(!events.some(e=>e.id===id))setEvents(current=>[sample,...current.slice(0,99)]);setSelected(events.find(e=>e.id===id)??sample);setWorkflowStatus('RUNNING');setWorkflowMessage(`${activeDirection} is evaluating ${id} with policy gates.`);addAudit('workflow.started',`${activeDirection} · ${id}`,'LIVE')
  if(activeDirection==='Hinglish voice recovery'){const text='Namaste! Aapka payment complete nahi hua. Main ek secure payment link share kar sakta hoon. Kya aap abhi retry karna chahenge?';if('speechSynthesis'in window){window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='hi-IN';u.rate=.94;u.onstart=()=>setVoicePlaying(true);u.onend=()=>setVoicePlaying(false);window.speechSynthesis.speak(u)}setVoicePlaying(true);window.setTimeout(()=>setVoicePlaying(false),5200);applyWorkflow(id,'COMPLETE','Consent-safe Hinglish script prepared. Browser voice demo only; no automatic call is placed.','Hinglish voice recovery');return}
  if(activeDirection==='Promise-to-pay tracker'){applyWorkflow(id,ptpState==='MISSED'?'ESCALATED':'COMPLETE',ptpState==='MISSED'?`Promise missed on ${ptpDate}; human escalation created.`:`Promise tracked through ${ptpDate}; reminder scheduled.`,ptpState==='MISSED'?'Escalate missed promise':'Track promised date');return}
  if(activeDirection==='Payment degradation'||activeDirection==='Checkout drop-off'){const action=activeDirection==='Checkout drop-off'?'Payment link':'Retry payment';try{const r=await fetch('/api/razorpay/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,transactionId:id,amount:sample.amount})});const data=await r.json();if(!r.ok)throw new Error(data?.error||'Razorpay Test Mode action failed');applyWorkflow(id,'COMPLETE',action==='Payment link'?`Test Mode payment link created: ${data.paymentLink||'ready'}. Payment remains unverified until checkout success.`:`Test Mode retry order ${data.orderId||'created'} is ready. Payment remains unverified until checkout success.`,action)}catch(err){applyWorkflow(id,'ESCALATED',err instanceof Error?err.message:'Test Mode action failed.',action)}return}
  window.setTimeout(()=>{const escalated=activeDirection==='B2B receivables chaser'&&sample.riskScore>=60;const verified=activeDirection==='Failed-subscription recovery'||activeDirection==='Mandate retry sequencer';applyWorkflow(id,escalated?'ESCALATED':'COMPLETE',escalated?'Risk boundary crossed; human AR escalation created.':`${activeDirection} completed in simulation with audit evidence attached.`,sample.action,verified?sample.amount:0)},650)}

 return <div className="app"><header className="nav"><div className="logo"><span className="logoMark">R</span><span>RazorRecover</span><em>AI</em></div><div className="navTabs">{['Overview','Simulation','Agent trace','Audit trail'].map(t=><button className={tab===t?'active':''} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="live"><span/>{running?`PROCESSING · ${Math.floor(progress)}%`:complete?'LIVE · COMPLETE':'LIVE · SYNTHETIC MODE'}</div></header>
 <main className="shell"><section className="hero"><div className="heroCopy"><div className="eyebrow">REVENUE RECOVERY / 01</div><h1>Recover revenue.<br/><i>Intelligently.</i></h1><p>An autonomous recovery agent that detects leakage, diagnoses root causes, applies bounded interventions, and proves the money recovered.</p></div><div className="heroAction"><div className="health"><span/> Shared recovery ledger <b>·</b> 42ms</div><button className="run" onClick={run} disabled={running}><span>{running?`Processing ${Math.floor(progress)}%`:complete?'Run again':'Run live simulation'}</span><b>↗</b></button></div></section>
 <section className="metrics"><Metric label="Revenue at risk" value={money(risk)} note={`${running?processed:100} synthetic events`}/><Metric label="Money recovered" value={money(recovered)} note="Verified recovery only" good/><Metric label="Recovery rate" value={`${rate}%`} note="Target: >30%" gold/><Metric label="Actions gated" value={String(stopped||8).padStart(2,'0')} note="Stopped / escalated" danger/></section>
 <section className="panel lab"><div className="panelTop"><div><span className="eyebrow">RECOVERY LAB</span><h2>Choose a failure environment</h2></div><span className="pulse">● shared ledger</span></div><div className="scenarioBar">{(Object.keys(scenarios) as Scenario[]).map(s=><button className={`scenario ${scenario===s?'active':''}`} onClick={()=>selectScenario(s)} key={s}><strong>{s==='balanced'?'01':s==='checkout'?'02':'03'}</strong>{scenarios[s].label}</button>)}</div><div className="scenarioMeta"><div><span>MODE</span><b>{scenarios[scenario].label}</b></div><div><span>POLICY</span><b>Bounded</b></div><div><span>DATA</span><b>100 events</b></div><div><span>FUNDS</span><b>Synthetic / Test Mode</b></div></div><div className="pulseChart"><span className="chartLabel">RECOVERY VELOCITY</span><span className="chartValue">{velocityLabel} verified</span><div className="spark"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={chart.map((v,i)=>`${i*(100/(chart.length-1))},${100-v}`).join(' ')}/><circle cx={100} cy={100-chart[chart.length-1]} r="2.3"/></svg></div></div></section>
 <section className="coreGrid"><div className="panel corePanel"><div className="panelTop"><div><span className="eyebrow">AGENT CORE</span><h2>Revenue recovery engine</h2></div><span className="secure">● BOUNDED · SAFE</span></div><RecoveryIntelligenceGraph transaction={cfTarget==='counterfactual'&&cfTransaction?cfTransaction:selected} progress={cfRunning?cfProgress:progress} running={cfRunning||running} complete={cfRunning?cfProgress>=100:complete}/></div><div className="panel tracePanel"><div className="panelTop"><div><span className="eyebrow">AI JUDGEMENT</span><h2>{tab==='Overview'?'Latest decisions':tab}</h2></div><span className="pulse">● {workflowStatus==='RUNNING'?'workflow running':'streaming'}</span></div>{tab==='Overview'&&<><div className="traceList"><Trace title="Root cause detected" text={`${selected?.direction||scenarios[scenario].label} · ${selected?.reason||'diagnosis pending'}`} tag={selected?`${selected.confidence}%`:'94%'}/><Trace title="Policy gate evaluated" text={selected?.explanation||'Idempotency ✓ · attempts 1/2 · low risk'} tag={selected?.policy==='Approved'?'SAFE':'ESCALATE'} stop={selected?.policy==='Escalated'}/><Trace title="Recovery workflow" text={selected?.workflowMessage||selected?.action||'Choose one of the seven directions below'} tag={selected?.workflowStatus||'READY'} stop={selected?.workflowStatus==='ESCALATED'}/><Trace title="Safety boundary" text={selected?.riskScore?`Risk ${selected.riskScore}/100 · no uncontrolled money movement`:'Retry limit reached · human escalation'} tag={selected?.riskScore&&selected.riskScore<70?'PASS':'STOP'} stop={!!selected?.riskScore&&selected.riskScore>=70}/></div><div className="policy"><span>SHARED RECOVERY LEDGER</span><b>Every workflow writes back to the same evidence chain.</b><div><i>✓</i> Metrics&nbsp;&nbsp; <i>✓</i> Graph&nbsp;&nbsp; <i>✓</i> Event stream&nbsp;&nbsp; <i>✓</i> Audit trail</div></div></>}{tab==='Simulation'&&<SimulationInfo progress={progress} running={running} scenario={scenarios[scenario].label}/>} {tab==='Agent trace'&&<AgentTrace progress={progress}/>} {tab==='Audit trail'&&<AuditTrail items={audit}/>}</div></section>
 <section className="panel playbooks" id="recovery-playbooks"><div className="panelTop"><div><span className="eyebrow">RECOVERY PLAYBOOKS / 07</span><h2>Seven first-class recovery directions</h2></div><span className="pulse">● click → shared ledger</span></div><div className="playbookGrid">{directions.map((d,i)=><button key={d.id} className={`playbookCard ${activeDirection===d.id?'active':''}`} onClick={()=>selectPlaybook(d.id)}><div className="playbookNumber">0{i+1}</div><div className="playbookCardTop"><strong>{d.short}</strong><span className={`playbookDot ${d.tone}`}>●</span></div><p>{d.description}</p><div className="playbookMeta"><span>{d.id}</span><b>{d.action}</b></div></button>)}</div>{activeDirection&&<div className="playbookConsole"><div className="playbookConsoleHead"><div><span className="eyebrow">ACTIVE WORKFLOW · SHARED LEDGER</span><h3>{directions.find(d=>d.id===activeDirection)?.short}</h3></div><button className="closePlaybook" onClick={()=>setActiveDirection(null)}>×</button></div><div className="workflowSteps">{directions.find(d=>d.id===activeDirection)!.steps.map((step,i)=><div key={step} className={`workflowStep ${workflowStatus!=='READY'&&i<=(workflowStatus==='RUNNING'?1:3)?'done':''}`}><span>0{i+1}</span><b>{step}</b></div>)}</div>{activeDirection==='Promise-to-pay tracker'&&<div className="ptpControls"><label>Promise date<input type="date" value={ptpDate} onChange={e=>setPtpDate(e.target.value)}/></label><label>Status<select value={ptpState} onChange={e=>setPtpState(e.target.value as typeof ptpState)}><option>PROMISED</option><option>PAID</option><option>MISSED</option></select></label></div>}{activeDirection==='Hinglish voice recovery'&&<div className="voicePanel"><span className="voiceWave">{voicePlaying?'))) ))) )))':'— — — —'}</span><p>“Namaste! Aapka payment complete nahi hua. Main ek secure payment link share kar sakta hoon. Kya aap abhi retry karna chahenge?”</p><small>Browser voice demo · consent-safe · no automatic call</small></div>}<div className="playbookActionRow"><div className={`workflowStatus ${workflowStatus.toLowerCase()}`}><span>●</span>{workflowStatus}</div><button className="run runPlaybook" onClick={runWorkflow} disabled={workflowStatus==='RUNNING'}>{directions.find(d=>d.id===activeDirection)!.action}<b>↗</b></button></div><div className="workflowMessage">{workflowMessage}</div></div>}</section>
 <section className="panel transactions"><div className="panelTop"><div><span className="eyebrow">EVENT STREAM / SHARED LEDGER</span><h2>Recovery operations</h2></div><span>{running?processed:100} / 100 synthetic transactions</span></div><div className="table">{visible.map(e=><button className={`row ${selected?.id===e.id?'selected':''}`} key={e.id} onClick={()=>setSelected(e)}><strong>{e.id}</strong><b>{money(e.amount)}</b><span>{e.reason}</span><span className="action">→ {e.workflowAction||e.action}</span><span className={`status ${e.result.toLowerCase()}`}>{e.workflowStatus&&e.workflowStatus!=='READY'?e.workflowStatus:e.result}</span><span className="confidence">{e.confidence}%</span></button>)}</div></section>
 {selected&&<section className="detailStrip"><div><span className="eyebrow">SELECTED EVENT</span><strong>{selected.id}</strong></div><div><small>RECOVERY DIRECTION</small><b>{selected.direction}</b></div><div><small>ROOT CAUSE</small><b>{selected.reason}</b></div><div><small>AI CONFIDENCE</small><b>{selected.confidence}%</b></div><div><small>RECOVERY PROB.</small><b>{selected.recoveryProbability}%</b></div><div><small>RISK SCORE</small><b>{selected.riskScore}/100</b></div><div><small>WORKFLOW</small><b className={selected.workflowStatus==='COMPLETE'?'goodText':selected.workflowStatus==='ESCALATED'?'dangerText':'goldText'}>{selected.workflowStatus||selected.result}</b></div></section>}
 {selected&&<AIRecoveryAdvisor transaction={selected}/>} {selected&&<DecisionExecutionSequence key={`${selected.id}-${selected.amount}-${selected.workflowStatus}`} amount={selected.amount}/>} {selected&&<CounterfactualLab originalTransaction={selected} onActiveGraphTargetChange={handleCfSync}/>}<footer>RAZORRECOVER AI · SYNTHETIC DATA · NO REAL CUSTOMER FUNDS · BUILDATHON PROTOTYPE</footer></main>{toast&&<div className="toast"><b>✓</b>{toast}</div>}</div>
}
function Metric({label,value,note,good,gold,danger}:{label:string,value:string,note:string,good?:boolean,gold?:boolean,danger?:boolean}){return <div className="metric"><span>{label}</span><strong className={good?'good':gold?'gold':danger?'danger':''}>{value}</strong><small>{note}</small></div>}
function Trace({title,text,tag,stop}:{title:string;text:string;tag:string;stop?:boolean}){return <div className="trace"><span className={stop?'dot stop':'dot'}/><div><b>{title}</b><small>{text}</small></div><em className={stop?'tag stopTag':'tag'}>{tag}</em></div>}
function SimulationInfo({progress,running,scenario}:{progress:number;running:boolean;scenario:string}){return <div className="infoView"><div className="bigProgress">{Math.floor(progress)}<small>%</small></div><p>{running?`Processing the ${scenario} environment through detection, diagnosis, decision, recovery and verification.`:'Launch the simulation to watch 100 synthetic transactions move through the complete recovery pipeline.'}</p><div className="miniStats"><span>100 <small>transactions</small></span><span>5 <small>AI stages</small></span><span>0 <small>real funds</small></span></div></div>}
function AgentTrace({progress}:{progress:number}){const lines=['Event ingested from payment stream','AI diagnosis requested','AI intervention recommendation received','Policy gate evaluated','Recovery action bounded and logged'];return <div className="traceList">{lines.map((line,i)=><div className="trace" key={line}><span className={progress>i*20?'dot':'dot muted'}/><div><b>{line}</b><small>{progress>i*20?'completed · evidence attached':'waiting for stage'}</small></div><em className="tag">{progress>i*20?'DONE':'WAIT'}</em></div>)}</div>}
function AuditTrail({items}:{items:AuditItem[]}){return <div className="audit">{(items.length?items:[{time:'—',event:'audit.ready',detail:'Run a batch or workflow to create shared evidence.',status:'INFO' as const}]).map((x,i)=><div key={`${x.time}-${i}`}><b>{x.time}</b><span>{x.event}</span><em>{x.detail}</em></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App />)
